create table if not exists public.payment_proofs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(telegram_id) on delete cascade,
  plan_code text not null,
  amount numeric(10,2) not null,
  status text not null default 'awaiting_proof',
  proof_file_id text,
  proof_type text,
  proof_message_id bigint,
  submitted_at timestamptz,
  reviewed_by bigint,
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists payment_proofs_user_status_idx
  on public.payment_proofs(user_id, status, created_at desc);
