-- True Stream V6 - Supabase schema

create table if not exists public.users (
  telegram_id bigint primary key,
  username text default '',
  first_name text default '',
  is_admin boolean not null default false,
  membership_plan text,
  membership_until timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  code text unique not null,
  user_id bigint not null references public.users(telegram_id) on delete cascade,
  storage_chat_id text not null,
  storage_message_id bigint not null,
  name text not null,
  mime text default 'application/octet-stream',
  size bigint default 0,
  created_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists links_user_created_idx on public.links(user_id, created_at);
create index if not exists links_expires_idx on public.links(expires_at);

create table if not exists public.payment_proofs (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(telegram_id) on delete cascade,
  plan_code text not null,
  amount numeric(10,2) not null,
  status text not null default 'awaiting_proof',
  proof_file_id text,
  proof_type text,
  proof_message_id bigint,
  created_at timestamptz not null default now(),
  submitted_at timestamptz,
  reviewed_by bigint,
  reviewed_at timestamptz
);

create index if not exists payment_proofs_user_status_idx
  on public.payment_proofs(user_id, status, created_at desc);
create index if not exists payment_proofs_status_idx
  on public.payment_proofs(status, created_at desc);

-- Lifetime counter used by /status. Expired link rows are deleted by cleanup,
-- so counting the links table alone would not represent total links ever generated.
create table if not exists public.bot_stats (
  id integer primary key,
  total_links_generated bigint not null default 0
);

insert into public.bot_stats (id, total_links_generated)
values (1, 0)
on conflict (id) do nothing;

create or replace function public.increment_total_links()
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare new_total bigint;
begin
  update public.bot_stats
  set total_links_generated = total_links_generated + 1
  where id = 1
  returning total_links_generated into new_total;
  return new_total;
end;
$$;

grant execute on function public.increment_total_links() to anon, authenticated, service_role;

grant select, insert, update, delete on public.users to anon, authenticated, service_role;
grant select, insert, update, delete on public.links to anon, authenticated, service_role;
grant select, insert, update, delete on public.payment_proofs to anon, authenticated, service_role;
grant select on public.bot_stats to anon, authenticated, service_role;

alter table public.users enable row level security;
alter table public.links enable row level security;
alter table public.payment_proofs enable row level security;
alter table public.bot_stats enable row level security;
